### ISSUE TITLE
Fix duplicate names behavior

### ISSUE THREAD

**Issue by rama-pang** [AY2223S1-CS2103T-T12-4/tp#213] opened 2022-10-19 23:46 UTC
Currently, `John Doe` and `John DOE` are considered two different names. Perhaps duplicate person checking should ignore upper case letters?

**Comment by izzahaj** [comment] 2022-10-24 05:43
I think this should also apply to other fields e.g. tags, conditions, tasks

**Comment by BlopApple** [comment] 2022-11-04 15:25
Closed as intended behaviour.

**Closed by BlopApple** 2022-11-04 15:25 UTC
Labels: type.Bug, severity.Medium
